### ISSUE TITLE
CKAN issues

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-support#87]
_From @Dargon606 on January 25, 2015 15:50_

Ive run into two issues while using CKAN

1. When installing certain mods (i noticed with B9 shuttle wings) it does not install mods that are required to use that mod (firespitter for B9 shuttle wings) even though on the mod page it is specificed that it will need that mod

2. I refresh and press mark all updated every so often but every time i do it it says it cannot update kerbalstats because its not installed. And it isnt the box for it isnt checked or anything. I dont use kerbal stats and i dont want to so to update my mods i have to go in download kerbal stats update then remove kerbal stats just because it wont let me do it otherwise

I hope you can get the second one fixed because it annoys me extremely.

_Copied from original issue: KSP-CKAN/CKAN#765_

**Comment by Dazpoet** [comment]
First part should be fixed. I'm wondering if the second was some kind of autodetection problem? A list of installed mods would be helpful but if the KSP install is a fluctuating as mine usually are I'd guess that'll be impossible by now?

**Comment by Dargon606** [comment]
Yes i have changed my entire mod install several times so yeah that is impossible but i'll check if i still get this problem next time my mods are updated. I believe i do but several updates ago i just finally gave up and installed kerbalstats because i didn't want to deal with it.

I believe the problem may emerge from being a recommended or suggested mod because even when i went through manually and checked the ones i wanted to update it would attempt to update kerbalstats. Would it be possible to identify mods that do that and i can tell you which ones of them i had at the time? (because i do vaguely remember the mods from it)

**Comment by Dazpoet** [comment]
The only thing that has a connection with KerbalStats is extraplanetary launchpads.

**Comment by Dargon606** [comment]
Well i did indeed have that. So that's possibly a cause of it.

**Comment by Dazpoet** [comment]
Tried playing around with some EPL files but I can't find a way to reproduce this problem. Should it happen again it would be helpful if you could check `ckan list` in a terminal to see if KerbalStats show up there. Also if the problem re-occurs you could try doing a `ckan upgrade --all` in terminal rather than doing it through gui just to see if the problem persists in both implementations.

**Comment by Dargon606** [comment]
Ok thank you for your time helping me out. And i will do so if this happens again.
